# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-21 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PSW', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commands',
            name='ip',
            field=models.CharField(max_length=25, verbose_name='IP'),
        ),
    ]
